import os
import re

# Use these commands to get the nuisance names
#sed -n 's/\(^[^ ].*[shape|lnN]\).*/\1/p' vhbb_VH_7p8TeV.txt > ! temp
#sed -i 's/\(.*\w\) .*[shape|lnN]/("\1",""),/' temp
#cat temp

nuisances = [
("FULL","FULL"),
("CMS_eff_b","BTAG"),
("CMS_eff_e","EFF"),
("CMS_eff_m","EFF"),
("CMS_fake_b","FAKE"),
("CMS_res_j","JER"),
("CMS_scale_j","JES"),
("CMS_scale_t","JES"),
("CMS_vhbb_MET_nojets","MET"),
("CMS_vhbb_QCD_SF_ZnunuHighPt_8TeV","SF2"),
("CMS_vhbb_QCD_SF_ZnunuLowPt_8TeV","SF2"),
("CMS_vhbb_QCD_SF_ZnunuMedPt_8TeV","SF2"),
("CMS_vhbb_ST","SF2"),
("CMS_vhbb_TT2_SF_7TeV","SF1"),
("CMS_vhbb_TTModel_Znn_8TeV","MODEL"),
("CMS_vhbb_TT_SF_1_7TeV","SF1"),
("CMS_vhbb_TT_SF_2_7TeV","SF1"),
("CMS_vhbb_TT_SF_7TeV","SF1"),
("CMS_vhbb_TT_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_TT_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_TT_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_TT_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_TT_SF_Zll_8TeV","SF1"),
("CMS_vhbb_TT_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_TT_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_TT_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_TT_ex","SF1"),
("CMS_vhbb_VV","SF2"),
("CMS_vhbb_WJSlope_Znn_8TeV","MODEL"),
("CMS_vhbb_WModel","MODEL"),
("CMS_vhbb_Wj0bModel_Wln_8TeV","MODEL"),
("CMS_vhbb_Wj0b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Wj0b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_Wj1bModel_Wln_8TeV","MODEL"),
("CMS_vhbb_Wj1b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Wj1b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_Wj2bModel_Wln_8TeV","MODEL"),
("CMS_vhbb_Wj2b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Wj2b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_WjHF2_SF_7TeV","SF1"),
("CMS_vhbb_WjHF_SF_1_7TeV","SF1"),
("CMS_vhbb_WjHF_SF_2_7TeV","SF1"),
("CMS_vhbb_WjHF_SF_7TeV","SF1"),
("CMS_vhbb_WjLF2_SF_7TeV","SF1"),
("CMS_vhbb_WjLF_SF_1_7TeV","SF1"),
("CMS_vhbb_WjLF_SF_2_7TeV","SF1"),
("CMS_vhbb_WjLF_SF_7TeV","SF1"),
("CMS_vhbb_Wln_res_j","JER"),
("CMS_vhbb_Wln_scale_j","JES"),
("CMS_vhbb_ZJModel_Znunu_1_7TeV","MODEL"),
("CMS_vhbb_ZJModel_Znunu_2_7TeV","MODEL"),
("CMS_vhbb_ZJSlope_Znn_8TeV","MODEL"),
("CMS_vhbb_Zj0b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_Zll_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Zj0b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_Zll_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Zj1b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_Zj2bModel_Znn_8TeV","MODEL"),
("CMS_vhbb_Zj2b_SF_WlnHighPt_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_WlnLowPt_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_WlnMidPt_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_Wtn_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_Zll_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_ZnunuHighPt_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_ZnunuLowPt_8TeV","SF1"),
("CMS_vhbb_Zj2b_SF_ZnunuMedPt_8TeV","SF1"),
("CMS_vhbb_ZjHF2_SF_7TeV","SF1"),
("CMS_vhbb_ZjHF_SF_1_7TeV","SF1"),
("CMS_vhbb_ZjHF_SF_2_7TeV","SF1"),
("CMS_vhbb_ZjHF_SF_7TeV","SF1"),
("CMS_vhbb_ZjHF_ex","SF1"),
("CMS_vhbb_ZjLF2_SF_7TeV","SF1"),
("CMS_vhbb_ZjLF_SF_1_7TeV","SF1"),
("CMS_vhbb_ZjLF_SF_2_7TeV","SF1"),
("CMS_vhbb_ZjLF_SF_7TeV","SF1"),
("CMS_vhbb_ZjLF_ex","SF1"),
("CMS_vhbb_Zll_res_j","JER"),
("CMS_vhbb_Zll_scale_j","JES"),
("CMS_vhbb_Znn_res_j","JER"),
("CMS_vhbb_Znn_scale_j","JES"),
("CMS_vhbb__VV","SF2"),
("CMS_vhbb_boost_EWK","SIG"),
("CMS_vhbb_boost_EWK_8TeV","SIG"),
("CMS_vhbb_boost_QCD","SIG"),
("CMS_vhbb_boost_QCD_8TeV","SIG"),
("CMS_vhbb_eff_b","BTAG"),
("CMS_vhbb_eff_e_8TeV","EFF"),
("CMS_vhbb_eff_m_8TeV","EFF"),
("CMS_vhbb_eff_t","EFF"),
("CMS_vhbb_fake_b_8TeV","FAKE"),
("CMS_vhbb_res_j_Wtn","JER"),
("CMS_vhbb_scale_j_Wtn","JES"),
("CMS_vhbb_statQCD_ZnunuHighPt_bin1_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuHighPt_bin2_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuHighPt_bin3_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuHighPt_bin4_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuHighPt_bin5_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuLowPt_bin1_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuLowPt_bin2_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuLowPt_bin3_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuLowPt_bin4_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuMedPt_bin1_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuMedPt_bin2_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuMedPt_bin3_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuMedPt_bin4_8TeV","STAT"),
("CMS_vhbb_statQCD_ZnunuMedPt_bin5_8TeV","STAT"),
("CMS_vhbb_statTT_WenHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statTT_WenHighPt_bin48_8TeV","STAT"),
("CMS_vhbb_statTT_WenMidPt_bin13_8TeV","STAT"),
("CMS_vhbb_statTT_WenMidPt_bin24_8TeV","STAT"),
("CMS_vhbb_statTT_Wenu","STAT"),
("CMS_vhbb_statTT_Wenu2","STAT"),
("CMS_vhbb_statTT_WmnHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statTT_WmnHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statTT_WmnMidPt_bin24_8TeV","STAT"),
("CMS_vhbb_statTT_Wmunu","STAT"),
("CMS_vhbb_statTT_Wmunu2","STAT"),
("CMS_vhbb_statTT_Wtn_8TeV","STAT"),
("CMS_vhbb_statTT_ZnunuHighPt_bin40_8TeV","STAT"),
("CMS_vhbb_statTT_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statTT_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statVVHF_WenHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statVVHF_WenHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statVVHF_WenMidPt_bin36_8TeV","STAT"),
("CMS_vhbb_statVVHF_WmnHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statVVHF_WmnHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statVVHF_Wtn_8TeV","STAT"),
("CMS_vhbb_statVVHF_ZnunuHighPt_bin40_8TeV","STAT"),
("CMS_vhbb_statVVHF_ZnunuLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statVVHF_ZnunuMedPt_bin32_8TeV","STAT"),
("CMS_vhbb_statVVLF_Wtn_8TeV","STAT"),
("CMS_vhbb_statVVLF_ZnunuHighPt_bin2_8TeV","STAT"),
("CMS_vhbb_statVV_Wenu","STAT"),
("CMS_vhbb_statVV_Wenu2","STAT"),
("CMS_vhbb_statVV_Wmunu","STAT"),
("CMS_vhbb_statVV_Wmunu2","STAT"),
("CMS_vhbb_statWH_Wenu","STAT"),
("CMS_vhbb_statWH_Wenu2","STAT"),
("CMS_vhbb_statWH_Wmunu","STAT"),
("CMS_vhbb_statWH_Wmunu2","STAT"),
("CMS_vhbb_statWH_Wtn_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin13_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin14_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin15_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin19_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin20_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin21_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin22_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statWj0b_WenMidPt_bin23_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin13_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin14_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin15_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin19_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin20_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin21_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin22_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin23_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statWj0b_WmnMidPt_bin16_8TeV","STAT"),
("CMS_vhbb_statWj0b_Wtn_8TeV","STAT"),
("CMS_vhbb_statWj0b_ZnunuHighPt_bin40_8TeV","STAT"),
("CMS_vhbb_statWj0b_ZnunuLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statWj0b_ZnunuMedPt_bin1_8TeV","STAT"),
("CMS_vhbb_statWj0b_ZnunuMedPt_bin32_8TeV","STAT"),
("CMS_vhbb_statWj1b_WenHighPt_bin23_8TeV","STAT"),
("CMS_vhbb_statWj1b_WenHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statWj1b_WenLowPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj1b_WmnMidPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj1b_Wtn_8TeV","STAT"),
("CMS_vhbb_statWj1b_ZnunuHighPt_bin2_8TeV","STAT"),
("CMS_vhbb_statWj1b_ZnunuMedPt_bin32_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin14_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin15_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin16_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin18_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin22_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin35_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenLowPt_bin45_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin17_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin18_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin19_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin21_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin22_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin33_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin34_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin35_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin46_8TeV","STAT"),
("CMS_vhbb_statWj2b_WenMidPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnHighPt_bin35_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnHighPt_bin36_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnHighPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin14_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin15_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin16_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin17_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin18_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin25_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin31_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin34_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin46_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin47_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnLowPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin17_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin18_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin19_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin20_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin33_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin34_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin36_8TeV","STAT"),
("CMS_vhbb_statWj2b_WmnMidPt_bin48_8TeV","STAT"),
("CMS_vhbb_statWj2b_Wtn_8TeV","STAT"),
("CMS_vhbb_statWj2b_ZnunuLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statWj2b_ZnunuMedPt_bin32_8TeV","STAT"),
("CMS_vhbb_statWjHF_Wenu","STAT"),
("CMS_vhbb_statWjHF_Wenu2","STAT"),
("CMS_vhbb_statWjHF_Wmunu","STAT"),
("CMS_vhbb_statWjHF_Wmunu2","STAT"),
("CMS_vhbb_statWjHF_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statWjHF_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statWjLF_Wenu","STAT"),
("CMS_vhbb_statWjLF_Wenu2","STAT"),
("CMS_vhbb_statWjLF_Wmunu","STAT"),
("CMS_vhbb_statWjLF_Wmunu2","STAT"),
("CMS_vhbb_statWjLF_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statWjLF_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statZH_Wtn_8TeV","STAT"),
("CMS_vhbb_statZH_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statZH_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statZj0b_Wtn_8TeV","STAT"),
("CMS_vhbb_statZj0b_ZnunuLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_statZj0b_ZnunuMedPt_bin32_8TeV","STAT"),
("CMS_vhbb_statZj1b_Wtn_8TeV","STAT"),
("CMS_vhbb_statZj1b_ZnunuHighPt_bin40_8TeV","STAT"),
("CMS_vhbb_statZj2b_Wtn_8TeV","STAT"),
("CMS_vhbb_statZjHF_Wenu","STAT"),
("CMS_vhbb_statZjHF_Wenu2","STAT"),
("CMS_vhbb_statZjHF_Wmunu","STAT"),
("CMS_vhbb_statZjHF_Wmunu2","STAT"),
("CMS_vhbb_statZjHF_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statZjHF_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statZjLF_Wenu","STAT"),
("CMS_vhbb_statZjLF_Wenu2","STAT"),
("CMS_vhbb_statZjLF_Wmunu","STAT"),
("CMS_vhbb_statZjLF_Wmunu2","STAT"),
("CMS_vhbb_statZjLF_Znunu_1_7TeV","STAT"),
("CMS_vhbb_statZjLF_Znunu_2_7TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin13_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin14_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin15_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin26_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin27_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin30_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin37_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin42_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin45_8TeV","STAT"),
("CMS_vhbb_statsTop_WenHighPt_bin48_8TeV","STAT"),
("CMS_vhbb_statsTop_WenLowPt_bin30_8TeV","STAT"),
("CMS_vhbb_statsTop_WenLowPt_bin32_8TeV","STAT"),
("CMS_vhbb_statsTop_WenLowPt_bin34_8TeV","STAT"),
("CMS_vhbb_statsTop_WenLowPt_bin36_8TeV","STAT"),
("CMS_vhbb_statsTop_WenMidPt_bin24_8TeV","STAT"),
("CMS_vhbb_statsTop_WenMidPt_bin48_8TeV","STAT"),
("CMS_vhbb_statsTop_Wenu","STAT"),
("CMS_vhbb_statsTop_Wenu2","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin16_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin26_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin29_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin31_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin38_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin43_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin44_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnHighPt_bin47_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnLowPt_bin35_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnLowPt_bin42_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnLowPt_bin44_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnLowPt_bin45_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnMidPt_bin12_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnMidPt_bin25_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnMidPt_bin44_8TeV","STAT"),
("CMS_vhbb_statsTop_WmnMidPt_bin45_8TeV","STAT"),
("CMS_vhbb_statsTop_Wmunu","STAT"),
("CMS_vhbb_statsTop_Wmunu2","STAT"),
("CMS_vhbb_stats_TT_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_TT_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_TT_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_TT_ZmmTight_7TeV","STAT"),
("CMS_vhbb_stats_Top_Wtn_8TeV","STAT"),
("CMS_vhbb_stats_Top_ZnunuHighPt_bin38_8TeV","STAT"),
("CMS_vhbb_stats_Top_ZnunuHighPt_bin39_8TeV","STAT"),
("CMS_vhbb_stats_Top_ZnunuLowPt_bin24_8TeV","STAT"),
("CMS_vhbb_stats_Top_ZnunuMedPt_bin31_8TeV","STAT"),
("CMS_vhbb_stats_Top_Znunu_1_7TeV","STAT"),
("CMS_vhbb_stats_Top_Znunu_2_7TeV","STAT"),
("CMS_vhbb_stats_VV_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_VV_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_VV_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_VV_ZmmTight_7TeV","STAT"),
("CMS_vhbb_stats_ZH_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_ZH_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_ZH_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_ZH_ZmmTight_7TeV","STAT"),
("CMS_vhbb_stats_ZjHF_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_ZjHF_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_ZjHF_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_ZjHF_ZmmTight_7TeV","STAT"),
("CMS_vhbb_stats_ZjLF_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_ZjLF_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_ZjLF_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_ZjLF_ZmmTight_7TeV","STAT"),
("CMS_vhbb_stats_bin14_TT_ZeeHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_TT_ZmmHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_VVLF_ZeeHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_VVLF_ZeeLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_VVLF_ZmmHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj0b_ZeeLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj0b_ZmmHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj0b_ZmmLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj1b_ZeeHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj1b_ZeeLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj1b_ZmmLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj2b_ZeeLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_Zj2b_ZmmLowPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_s_Top_ZeeHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_s_Top_ZmmHighPt_8TeV","STAT"),
("CMS_vhbb_stats_bin14_s_Top_ZmmLowPt_8TeV","STAT"),
("CMS_vhbb_stats_s_Top_ZeeLoose_7TeV","STAT"),
("CMS_vhbb_stats_s_Top_ZeeTight_7TeV","STAT"),
("CMS_vhbb_stats_s_Top_ZmmLoose7TeV","STAT"),
("CMS_vhbb_stats_s_Top_ZmmTight_7TeV","STAT"),
("CMS_vhbb_trigger_CSV_Znn_8TeV","BTAG"),
("CMS_vhbb_trigger_CSV_fake_Znn_8TeV","FAKE"),
("CMS_vhbb_trigger_MET","MET"),
("CMS_vhbb_trigger_MET_Znn_8TeV","MET"),
("CMS_vhbb_trigger_MET_tau","MET"),
("QCDscale_QCD","MODEL"),
("QCDscale_VH","MODEL"),
("QCDscale_VV","MODEL"),
("QCDscale_WH","MODEL"),
("QCDscale_ZH","MODEL"),
("QCDscale_ttbar","MODEL"),
("UEPS","LUMI"),
("lumi_7TeV","LUMI"),
("lumi_7TeV_7TeV","LUMI"),
("lumi_8TeV","LUMI"),
("pdf_gg","MODEL"),
("pdf_qqbar","MODEL"),
]

#orig = "vhbb_Znn_8TeV.txt"
#test = "test_8TeV.txt"
orig = "vhbb_VH_7p8TeV.txt"
test = "test_7p8TeV.txt"
comm1 = "combine -M MaxLikelihoodFit -m 125 --robustFit=1 --stepSize=0.05 --rMin=-5 --rMax=5 -t -1 --expectSignal=1 "
comm2 = "combine -M ProfileLikelihood -m 125 --signif --pvalue -t -1 --expectSignal=1 "
log1 = "syst_mu.log"
log2 = "syst_sig.log"
quantify1 = []
quantify2 = []

nuisances_1 = []
nuisances_2 = []
for n1, n2 in nuisances:
    if n2 in nuisances_2:
        nuisances_1[nuisances_2.index(n2)].append(n1)
    else:
        nuisances_1.append([n1])
        nuisances_2.append(n2)

for i in xrange(len(nuisances_1)):
    print nuisances_2[i]
    print nuisances_1[i]


for nui, nn in zip(nuisances_2, nuisances_1):
    os.system("cp " + orig + " " + test)
    os.system("sed -i 's/^kmax.*/kmax */' " + test)
    writeme = []
    with open(test,"r") as f:
        for line in f:
            for n in nn:
                line = line.replace(n, "#"+n)
            writeme.append(line)
    with open(test,"w") as f:
        f.write('\n'.join(writeme))
    
    os.system(comm1 + test + " > %s" % log1)
    os.system(comm2 + test + " > %s" % log2)

    with open(log1) as f:
        for line in f:
            m = re.match("Best fit r: (.*)  (.*)/(.*)  \(68% CL\)", line)
            if m:
                sigma = (float(m.group(2)) * -1. + float(m.group(3))) / 2
                print nui, m.group(2), m.group(3), sigma 
                if not quantify1:
                    quantify1.append((nui, sigma, sigma/sigma))
                else:
                    quantify1.append(("NO "+nui, sigma, sigma/quantify1[0][1]))

    with open(log2) as f:
        for line in f:
            m = re.match("       \(Significance = (.*)\)", line)
            if m:
                signif = float(m.group(1))
                print nui, m.group(1)
                if not quantify2:
                    quantify2.append((nui, signif, signif/signif))
                else:
                    quantify2.append(("NO "+nui, signif, signif/quantify2[0][1]))

print "metric: mu uncertainty"
quantify1.sort(key=lambda tup: tup[2], reverse=True)
for q in quantify1:
    print "%-40s %.4f %.4f" % (q[0], q[1], q[2]*100.)

print "metric: significance"
quantify2.sort(key=lambda tup: tup[2], reverse=True)
for q in quantify2:
    print "%-40s %.4f %.4f" % (q[0], q[1], q[2]*100.)
