combineCards.py ZnunuHighPt_8TeV=zhinv_Zbb_J14_bbb_ZnunuHighPt_8TeV.txt ZnunuMedPt_8TeV=zhinv_Zbb_J14_bbb_ZnunuMedPt_8TeV.txt ZnunuLowPt_8TeV=zhinv_Zbb_J14_bbb_ZnunuLowPt_8TeV.txt > ! zhinv_Zbb_J14_bbb_combo_8TeV.txt
combineCards.py ZnunuHighPt_8TeV=zhinv_Zbb_J14_bbb_ZnunuHighPt_8TeV.txt ZnunuMedPt_8TeV=zhinv_Zbb_J14_bbb_ZnunuMedPt_8TeV.txt > ! zhinv_Zbb_J14_bbb_combo2_8TeV.txt

combineCards.py ZnunuHighPt_8TeV=zhinv_Zbb_SI_J14_bbb_ZnunuHighPt_8TeV.txt ZnunuMedPt_8TeV=zhinv_Zbb_SI_J14_bbb_ZnunuMedPt_8TeV.txt ZnunuLowPt_8TeV=zhinv_Zbb_SI_J14_bbb_ZnunuLowPt_8TeV.txt > ! zhinv_Zbb_SI_J14_bbb_combo_8TeV.txt
combineCards.py ZnunuHighPt_8TeV=zhinv_Zbb_SI_J14_bbb_ZnunuHighPt_8TeV.txt ZnunuMedPt_8TeV=zhinv_Zbb_SI_J14_bbb_ZnunuMedPt_8TeV.txt > ! zhinv_Zbb_SI_J14_bbb_combo2_8TeV.txt
