root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv105\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv115\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv125\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv135\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv145\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZbbHinv150\",\"BDT\"\)

#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH110\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH115\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH120\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZnnH125\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH130\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH135\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH140\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH145\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"ZnnH150\",\"BDT\"\)

#root -b -l -q ./BSMTrimTree.C+\(\"WlnH110\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH115\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH120\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"WlnH125\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH130\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH135\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH140\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH145\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"WlnH150\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"WW\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"WZ\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZZ\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"T_t\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"Tbar_t\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"T_s\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"Tbar_s\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"T_tW\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"Tbar_tW\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"QCDPt50\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt80\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt120\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt170\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt300\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt470\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt600\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt800\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt1000\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt1400\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"QCDPt1800\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"WJetsPtW70\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZJetsHT50\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZJetsHT100\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZJetsHT200\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZJetsHT400\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"WJetsHW\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"ZJetsHW\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"TTPowheg\",\"BDT\"\)
#root -b -l -q ./BSMTrimTree.C+\(\"TTMCatNLO\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"TTHadronicMG\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"WJetsPtW100\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"WJetsPtW180\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"ZJetsPtZ100\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"TTFullLeptMG\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"TTSemiLeptMG\",\"BDT\"\)

root -b -l -q ./BSMTrimTree.C+\(\"Data_P\",\"BDT\"\)
root -b -l -q ./BSMTrimTree.C+\(\"Data_R\",\"BDT\"\)
